kind: Pod
apiVersion: v1
metadata:
  name: test-pod2
spec:
  containers:
  - name: test-pod2
    image: docker.io/aarch64/busybox:latest
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/SUCCESSAGAIN && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim
