apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pv
spec:
  storageClassName: manualnfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: pihole-pv
