apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: b8kery-nfs-pihole-pv
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: b8kery-nfs-pihole-pv
