apiVersion: v1
kind: PersistentVolume
metadata:
  name: b8kery-nfs-pihole-pv
  labels:
    volume: b8kery-nfs-pihole-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/b8kery-nfs-pihole
    server: 192.168.0.10
