apiVersion: v1
kind: Service
metadata:
  name: pihole-svc-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: PiHoleShared
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.201
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 53
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    app: pihole
