apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  labels:
    volume: pihole-pv
spec:
  storageClassName: manualnfs
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/b8kery-pihole
    server: 192.168.0.10
