apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-test
  labels:
    volume: nfs-pv-test
spec:
  storageClassName: manualnfs
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /volume1/b8kery-nfs-test
    server: 192.168.0.10
