apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-test
spec:
  storageClassName: manualnfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: nfs-pv-test
