apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nfs-pv-test
        persistentVolumeClaim:
          claimName: nfs-pv-test
      containers:
      - name: nginx
        image: nginx
        ports:
          - name: "nginx-server"
            containerPort: 80
        volumeMounts:
          - name: nfs-pv-test
            mountPath: "/usr/share/nginx/html"

